name: 'allure-html-reporter-aws-s3-website'
description: 'Allure HTML Test Results with history to publish to AWS S3 Bucket'
author: 'Pavan Mudigonda, forked by clarity movement'
branding:
  icon: 'layout'
  color: 'green'
inputs:
  allure_results:
    description: 'Allure test result data dir'
    required: true
    default: 'allure-results'
  allure_report:
    description: 'Allure report target dir'
    required: true
    default: 'allure-report'
  allure_history:
    description: 'Folder for allure history'
    required: true
    default: 'allure-history'
  keep_reports:
    description: 'Keep X last reports'
    required: false
    default: '20'    
  github_run_num:
    description: 'GitHub Actions build number'
    required: true
    default: ${{ github.run_number }}
  github_run_id:
    description: 'GitHub Actions run id'
    required: true
    default: ${{ github.run_id }}
  report_url:
    description: 'Use a custom URL instead of *.github.io'
    required: false
    default: ''
  latest_dest:
    description: 'Destination for latest report'
    required: false
    default: 'latest'
  matrix_dir:
    description: 'Directory to adjust for matrix runs'
    required: false
    default: ''
  component:
    description: 'Component name'
    required: false
    default: ''
  version:
    description: 'Component version'
    required: false
    default: ''
  project:
    description: 'Project name'
    required: false
    default: 'snowman'
runs:
  using: 'docker'
  image: 'Dockerfile'
